"""
Title:  Gas Station

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.



Example:
Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

"""


class Solution:

    def findTheDifference(self, s: str, t: str) -> str:
        if s is not None and t is not None:
            s_char_freq_map, t_char_freq_map = {}, {}

            for i in range(len(s)):
                s_char_freq_map[s[i]] = s_char_freq_map.get(s[i], 0) + 1
            for i in range(len(t)):
                t_char_freq_map[t[i]] = t_char_freq_map.get(t[i], 0) + 1

            for k, v in t_char_freq_map.items():
                if s_char_freq_map.get(k) != v:
                    return k
        else:
            return None


def test(got, expected):
    if got == expected:
        prefix = ' OK '
    else:
        prefix = '  X '
    print('{} got: {} expected: {}'.format(prefix, repr(got), repr(expected)))


if __name__ == "__main__":
    solution = Solution()

    test(solution.findTheDifference(None, None), None)
    test(solution.findTheDifference(None, "abcde"), None)
    test(solution.findTheDifference("abcd", None), None)
    test(solution.findTheDifference("", "e"), "e")
    test(solution.findTheDifference("e", ""), None)
    test(solution.findTheDifference("abcd", "abcde"), "e")
    test(solution.findTheDifference("a", "aa"), "a")
